pub const DEVICE_CODE_LENGTH : usize = 6;
pub const SHOCKER_DEFAULT_POWER : i32 = 5;
pub const TOKEN_EXPIRATION_DAYS : usize = 30;
pub const MAX_SHUFFLE_COUNT : u32 = 5;
pub const CODE_CHECK_INTERVAL_TIME_IN_SEC : u64 = 30;
pub const CODE_EXPIRATION_TIME_IN_MIN : i64 = 2;
pub const EVENT_LOOP_INTERVAL_TIME_IN_MS : u64 = 250;
